OnlineShop/OnlineShop/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Areas.Customer.Models;
using OnlineShop.Data;
using System.Linq;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private ApplicationDbContext _db;
        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult OrderDetails()
        {
            var data = (from OD in _db.orderDetails
                        join O in _db.order on OD.OrderId equals O.Id
                        join P in _db.products on OD.ProductId equals P.Id
                        join Payment in _db.payments on O.Id equals Payment.OrderId into paymentGroup
                        from payment in paymentGroup.DefaultIfEmpty()  // Left join
                        select new OrdersDetails
                        {
                            Id = OD.Id,
                            //OrderId = O.Id,
                            //ProductId = P.Id,
                            OrderNo = O.OrderNo,
                            CustomerName = O.Name,
                            PhoneNo = O.PhoneNo,
                            Email = O.Email,
                            Address = O.Address,
                            OrderDate = O.OrderDate,
                            ProductName = P.Name,
                            Price = P.Price,
                            Image = P.Image,
                            ProductColor = P.ProductColor,
                            TransactionId = payment != null ? payment.TransactionId : null,
                            OrderStatus = OD.OrderStatus
                        }).OrderByDescending(x => x.Id).ToList();

            return View(data);
        }
        [HttpGet]
        public IActionResult Confirmed(OrdersDetails ordersDetails) 
        {
            var getData = _db.orderDetails.FirstOrDefault(x => x.Id == ordersDetails.Id);
            getData.OrderStatus = "Confirmed";
            _db.orderDetails.Update(getData);
            _db.SaveChanges();
            return Redirect("/Admin/Order/OrderDetails");
        }
    }
}

OnlineShop/OnlineShop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private ApplicationDbContext _db;
        private IHostingEnvironment _he;
        public ProductController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(_db.products.Include(c=>c.ProductTypes).Include(f=>f.SpecialTags).ToList());
        }
        //Post Index Action Method
        [HttpPost]
        public IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var products = _db.products.Include(c => c.ProductTypes).Include(f => f.SpecialTags)
                .Where(c=>c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            if (lowAmount == null || largeAmount == null)
            {
                products = _db.products.Include(c => c.ProductTypes).Include(f => f.SpecialTags).ToList();
            }
            return View(products);
        }
        //Get Create Method
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["ProductTypeId"] = new SelectList(_db.productTypes.ToList(),"Id","productType"); 
            ViewData["TagId"] = new SelectList(_db.specialTags.ToList(),"Id", "ProductTag"); 
            return View();
        }
        //Post Create Method
        [HttpPost]
        public async Task<IActionResult> Create(Products products,IFormFile image)
        {
            if (ModelState.IsValid)
            {
                var searchProduct = _db.products.FirstOrDefault(c => c.Name == products.Name);
                if(searchProduct != null)
                {
                    ViewBag.message = "This Product is already exist";
                    ViewData["ProductTypeId"] = new SelectList(_db.productTypes.ToList(), "Id", "productType");
                    ViewData["TagId"] = new SelectList(_db.specialTags.ToList(), "Id", "ProductTag");
                    return View(products);
                }
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath+"/Images",Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/"+image.FileName;
                }
                if (image == null)
                {
                    products.Image = "Images/noimage.png";
                }
                _db.products.Add(products);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product Saved Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        //Get Edit Method
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            ViewData["ProductTypeId"] = new SelectList(_db.productTypes.ToList(), "Id", "productType");
            ViewData["TagId"] = new SelectList(_db.specialTags.ToList(), "Id", "ProductTag");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.products.Include(c => c.ProductTypes).Include(f => f.SpecialTags).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        //Post Edit Method
        [HttpPost]
        public async Task<IActionResult> Edit(Products products,IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath+"/Images",Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/"+image.FileName;
                }
                if (image == null)
                {
                    products.Image = "Images/noimage.png";
                }
                _db.products.Update(products);
                await _db.SaveChangesAsync();
                TempData["update"] = "Product Updated Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        //Get Details Action Method
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var product = _db.products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //Get Delete Action Method
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        //Post Delete Action Method
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.products.FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _db.products.Remove(product);
            await _db.SaveChangesAsync();
            TempData["delete"] = "Product Deleted Successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShop/OnlineShop/Areas/Admin/Controllers/SpecialTagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SpecialTagsController : Controller
    {
        private ApplicationDbContext _db;
        public SpecialTagsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.specialTags.ToList());
        }

        //Create Get Action Method
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        //Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                _db.specialTags.Add(specialTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }

        //Edit Get Action Method
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productTag = _db.specialTags.Find(id);
            if (productTag == null)
            {
                return NotFound();
            }
            return View(productTag);
        }
        //Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                _db.Update(specialTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }

        //Details Get Action Method
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productTag = _db.specialTags.Find(id);
            if (productTag == null)
            {
                return NotFound();
            }
            return View(productTag);
        }

        //Details Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(SpecialTags specialTags)
        {
            return RedirectToAction(nameof(Index));
        }

        //Details Get Action Method
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productTag = _db.specialTags.Find(id);
            if (productTag == null)
            {
                return NotFound();
            }
            return View(productTag);
        }

        //Delete Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, SpecialTags specialTags)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != specialTags.Id)
            {
                return NotFound();
            }
            var productTag = _db.specialTags.Find(id);
            if (productTag == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(productTag);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTag);
        }
    }
}

OnlineShop/OnlineShop/Views/Shared/_ButtonPartial.cshtml
@model int
@{
    ViewData["Title"] = "ButtonPartial";
}

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model"><i class="far fa-edit"></i></a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list"></i></a>
        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash"></i></a>
    </div>
</td>

OnlineShop/OnlineShop/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using OnlineShop.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
    {
        products = new List<Products>();
    }
    count = products.Count(); 
}  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DIU Store</title>
    <link rel="icon" type="image/x-icon" href="https://drive.google.com/file/d/1sJ2m7oGi3ahBXTRiXGmgi6ln3nLhTTHt/view?usp=sharing">
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css"/>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <style>
        .error{
            color:red;
            font-weight:bold;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DIU <span class="text-success">Store</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if(userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Product Tags</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="User" asp-action="Index">User List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="OrderDetails">Order Details</a>
                            </li>
                        }
                        @if (userRole == "User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">
                                    <i class="fas fa-shopping-cart"></i>
                                    (@count)
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Order" asp-action="OrderDetails">
                                    Order Details
                                </a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

OnlineShop/OnlineShop/Views/Shared/_PartialView.cshtml
@model string
@{
    ViewData["Title"] = "PartialView";
}

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model"><i class="far fa-edit"></i></a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list"></i></a>
        <a asp-action="Lockout" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash"></i></a>
    </div>
</td>